const products = [
  { id: 1, name: "Laptop" },
  { id: 2, name: "Phone" },
  { id: 3, name: "Keyboard" },
  { id: 4, name: "Mouse" },
  { id: 5, name: "Monitor" },
  { id: 6, name: "Headphones" },
  { id: 7, name: "Speaker" },
  { id: 8, name: "Camera" },
  { id: 9, name: "Printer" },
  { id: 10, name: "Tablet" },
  { id: 11, name: "Smart Watch" },
  { id: 12, name: "Microphone" },
  { id: 13, name: "SSD" },
  { id: 14, name: "Hard Disk" },
  { id: 15, name: "Power Bank" },
  { id: 16, name: "Router" },
  { id: 17, name: "Webcam" },
  { id: 18, name: "Projector" },
  { id: 19, name: "Charger" },
  { id: 20, name: "USB Cable" },
  { id: 21, name: "Gaming Chair" },
  { id: 22, name: "Graphics Card" },
  { id: 23, name: "CPU Cooler" },
  { id: 24, name: "RAM" },
  { id: 25, name: "Motherboard" },
  { id: 26, name: "Drone" },
  { id: 27, name: "VR Headset" },
  { id: 28, name: "Joystick" },
  { id: 29, name: "TV" },
  { id: 30, name: "AirPods" },
  { id: 18, name: "Projector" },
  { id: 19, name: "Charger" },
  { id: 20, name: "USB Cable" },
  { id: 21, name: "Gaming Chair" },
  { id: 22, name: "Graphics Card" },
  { id: 23, name: "CPU Cooler" },
  { id: 24, name: "RAM" },
  { id: 25, name: "Motherboard" },
  { id: 26, name: "Drone" },
  { id: 27, name: "VR Headset" },
  { id: 28, name: "Joystick" },
  { id: 29, name: "TV" },
  { id: 30, name: "AirPods" },
  { id: 1, name: "Laptop" },
  { id: 2, name: "Phone" },
  { id: 3, name: "Keyboard" },
  { id: 4, name: "Mouse" },
  { id: 5, name: "Monitor" },
  { id: 6, name: "Headphones" },
  { id: 7, name: "Speaker" },
  { id: 8, name: "Camera" },
  { id: 9, name: "Printer" },
  { id: 10, name: "Tablet" },
  { id: 11, name: "Smart Watch" },
  { id: 12, name: "Microphone" },
  { id: 13, name: "SSD" },
  { id: 14, name: "Hard Disk" },
  { id: 15, name: "Power Bank" },
  { id: 16, name: "Router" },
  { id: 17, name: "Webcam" },
  { id: 18, name: "Projector" },
  { id: 19, name: "Charger" },
  { id: 20, name: "USB Cable" },
  { id: 21, name: "Gaming Chair" },
  { id: 22, name: "Graphics Card" },
  { id: 23, name: "CPU Cooler" },
  { id: 24, name: "RAM" },
  { id: 25, name: "Motherboard" },
  { id: 26, name: "Drone" },
  { id: 27, name: "VR Headset" },
  { id: 28, name: "Joystick" },
  { id: 29, name: "TV" },
  { id: 30, name: "AirPods" },
  { id: 18, name: "Projector" },
  { id: 19, name: "Charger" },
  { id: 20, name: "USB Cable" },
  { id: 21, name: "Gaming Chair" },
  { id: 22, name: "Graphics Card" },
  { id: 23, name: "CPU Cooler" },
  { id: 24, name: "RAM" },
  { id: 25, name: "Motherboard" },
  { id: 26, name: "Drone" },
  { id: 27, name: "VR Headset" },
  { id: 28, name: "Joystick" },
  { id: 29, name: "TV" },
  { id: 30, name: "AirPods" }

];

export default products